### PR TITLE
Rename/credentials to access tokens

### PR DESCRIPTION
**Pull request by toymachiner62**

### CODE REVIEW

**Comment by benblair** [comment]
Should all references to `Credentials` be gone? I might have the wrong context here...

**Comment by toymachiner62** [comment]
> Should all references to `Credentials` be gone? I might have the wrong context here...

Yes this rename's the client, entities, method names, etc from Credentials to Access Tokens. Is there something you're seeing that's not gone?

**Comment by benblair** [comment]
Lines [5](https://github.com/catalyticlabs/catalytic-sdk-php/pull/42/files#diff-506273ffbb5650f6f934b700c1501c35R5), [35 and 36](https://github.com/catalyticlabs/catalytic-sdk-php/pull/42/files#diff-506273ffbb5650f6f934b700c1501c35R35-R36) of CatalyticClient.php

**Comment by toymachiner62** [comment]
> Lines [5](https://github.com/catalyticlabs/catalytic-sdk-php/pull/42/files#diff-506273ffbb5650f6f934b700c1501c35R5), [35 and 36](https://github.com/catalyticlabs/catalytic-sdk-php/pull/42/files#diff-506273ffbb5650f6f934b700c1501c35R35-R36) of CatalyticClient.php

@benblair So that is actually an internal file that is used to fetch the access token either from the env var, a file, or directly being passed in. It was really confusing when access token's were called credentials prior to this PR, so I thought i'd leave it as credentials unless you have a better name for it.

**Comment by benblair** [comment]
Ah ok. Yea that seems fine.

**Pull request merged**
